# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
tilt1:
  ID: 1
  Return_Delay_Time: 0
tilt2:
  ID: 2
  Return_Delay_Time: 0
tilt3:
  ID: 3
  Return_Delay_Time: 0
tilt4:
  ID: 4
  Return_Delay_Time: 0
tilt5:
  ID: 5
  Return_Delay_Time: 0
tilt6:
  ID: 6
  Return_Delay_Time: 0
